version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: universidade_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: admissoes
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: universidade_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=adminpassword
      - DB_NAME=admissoes
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
